name: Update README from projects.json

on:
  push:
    paths:
      - 'projects.json'
      - 'LungWai/projects.json'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r LungWai/requirements.txt

      - name: Regenerate README
        run: |
          python LungWai/generate_readme.py

      - name: Sync Neon DB (or write mirror JSON)
        env:
          NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
          NEON_TABLE: ${{ secrets.NEON_TABLE }}
        run: |
          python LungWai/sync_neon_db.py || true

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add readme.md LungWai/db_products.json || true
            git commit -m "chore: regenerate README and sync Neon (mirror if no DB)"
            git push
          else
            echo "No changes to commit"
          fi

      - name: Notify dependent repo (optional)
        if: ${{ success() && env.DEPENDENT_REPO != '' }}
        env:
          DEPENDENT_REPO: ${{ secrets.DEPENDENT_REPO }}
          DISPATCH_TOKEN: ${{ secrets.DEPENDENT_REPO_PAT }}
          SRC_REPO: ${{ github.repository }}
          SRC_REF: ${{ github.ref_name }}
        run: |
          if [ -n "$DISPATCH_TOKEN" ] && [ -n "$DEPENDENT_REPO" ]; then
            curl -sS -X POST \
              -H "Authorization: token $DISPATCH_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${DEPENDENT_REPO}/dispatches \
              -d "{\"event_type\":\"projects_json_updated\",\"client_payload\":{\"source_repo\":\"${SRC_REPO}\",\"ref\":\"${SRC_REF}\"}}"
          else
            echo "Skipping repository_dispatch; secrets not configured."
          fi 