name: Update README from projects.json

on:
  push:
    paths:
      - 'LungWai/projects.json'
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r LungWai/requirements.txt

      - name: Regenerate README
        run: |
          python LungWai/generate_readme.py

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git add -A
            git commit -m "chore: regenerate README from projects.json"
            git push
          else
            echo "No changes to commit"
          fi 