name: Prune old Vercel deployments

on:
  schedule: [{ cron: "0 6 * * *" }]
  workflow_dispatch:

env:
  KEEP: "5"
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets
        id: check
        run: |
          set -euo pipefail
          missing=()
          [ -z "${{ secrets.VERCEL_TOKEN }}" ] && missing+=(VERCEL_TOKEN)
          [ -z "${{ secrets.VERCEL_PROJECT_ID }}" ] && missing+=(VERCEL_PROJECT_ID)
          if [ ${#missing[@]} -gt 0 ]; then
            echo "Required secrets missing: ${missing[*]}"
            echo "ok=false" >> "$GITHUB_OUTPUT"
          else
            echo "ok=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Install jq
        if: steps.check.outputs.ok == 'true'
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Delete deployments beyond last ${{ env.KEEP }}
        if: steps.check.outputs.ok == 'true'
        shell: bash
        run: |
          set -euo pipefail
          BASE="https://api.vercel.com"
          AUTH=( -H "Authorization: Bearer ${VERCEL_TOKEN}" )
          q_team=""; [ -n "${VERCEL_TEAM_ID:-}" ] && q_team="&teamId=${VERCEL_TEAM_ID}"
          prune () {
            target="$1"
            list_url="${BASE}/v6/deployments?projectId=${VERCEL_PROJECT_ID}&target=${target}&limit=200${q_team}"
            mapfile -t ids < <(curl -fsSL "${AUTH[@]}" "$list_url" \
              | jq -r '.deployments | sort_by(.createdAt) | reverse | .[] | select(.state=="READY") | .uid')
            count=${#ids[@]}; (( count <= KEEP )) && { echo "Nothing to delete for ${target}"; return; }
            for uid in "${ids[@]:${KEEP}}"; do
              del_url="${BASE}/v13/deployments/${uid}"; [ -n "${VERCEL_TEAM_ID:-}" ] && del_url="${del_url}?teamId=${VERCEL_TEAM_ID}"
              echo "Deleting ${target} ${uid}"
              curl -fsS -X DELETE "${AUTH[@]}" "$del_url" > /dev/null
            done
          }
          prune production
          prune preview 